# Site setings
name: 'Mariposa Lightfeather'
description: 
meta_description: 
greetings: 
logo: 'assets/images/logoSquareYellowHang.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://mariposalightfeather.com/
disqus:
mailchimp_url: 
cover_image: 'covers/bigLogoShort.png'
# Add your GA Tracking Id
ga_analytics: 'G-X9G6FBE2NE'

# Contact form setings
email: mariposa@mariposalightfeather@gmail.com
contact_page_description: "Follow me on Twitter and Instagram.  Or contact me."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'MariposaLight'
instagram: 'MariposaLightfeather'

# Navigation
navigation:
#  - text: About
#    url: /about
#  - text: Episodes
#    url: /episodes
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed